// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNV7umkkApKvp47JSahVKqWjWqh1f6wM',
    appId: '1:951809059222:android:31a112f4e2738525ad15b7',
    messagingSenderId: '951809059222',
    projectId: 'bingbong-7edf4',
    storageBucket: 'bingbong-7edf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD-qdYU5IPNFyZoFeMLYlxy-bYU2LWv0s',
    appId: '1:951809059222:ios:99f62d0de6cb0011ad15b7',
    messagingSenderId: '951809059222',
    projectId: 'bingbong-7edf4',
    storageBucket: 'bingbong-7edf4.appspot.com',
    iosClientId: '951809059222-6pho81tilj020bb7mou19htamq0t1t6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoRecordUpload',
  );
}
